import {
  FaCalendarCheck,
  FaChartLine,
  FaClipboardList,
  FaExclamationTriangle,
  FaFileInvoiceDollar,
  FaHotel,
  FaKaaba,
  FaMoneyBillWave,
  FaPlusCircle,
  FaPassport,
  FaPlaneDeparture,
  FaReceipt,
  FaShoppingBag,
  FaTasks,
  FaTicketAlt,
  FaUndo,
  FaUsers,
} from 'react-icons/fa';

import { MODULE_KEYS } from '../../../utils/moduleConfig';

export const TRAVEL_CARD_CATEGORIES = Object.freeze({
  FINANCIAL: 'financial',
  OPERATIONAL: 'operational',
});

export const travelToneClasses = Object.freeze({
  bookings: {
    accentClass: 'from-sky-500 to-cyan-500',
    borderClass: 'border-sky-100',
    surfaceClass: 'from-sky-50/90 via-white to-cyan-50/70',
    iconClass: 'bg-sky-600 text-white ring-sky-200 shadow-sky-100',
    textClass: 'text-sky-700',
    rowClass: 'border-sky-100 bg-sky-50/80',
  },
  sales: {
    accentClass: 'from-blue-500 to-indigo-500',
    borderClass: 'border-blue-100',
    surfaceClass: 'from-blue-50/90 via-white to-indigo-50/70',
    iconClass: 'bg-blue-600 text-white ring-blue-200 shadow-blue-100',
    textClass: 'text-blue-700',
    rowClass: 'border-blue-100 bg-blue-50/80',
  },
  received: {
    accentClass: 'from-emerald-500 to-teal-500',
    borderClass: 'border-emerald-100',
    surfaceClass: 'from-emerald-50/90 via-white to-teal-50/70',
    iconClass: 'bg-emerald-600 text-white ring-emerald-200 shadow-emerald-100',
    textClass: 'text-emerald-700',
    rowClass: 'border-emerald-100 bg-emerald-50/80',
  },
  due: {
    accentClass: 'from-amber-500 to-orange-500',
    borderClass: 'border-amber-100',
    surfaceClass: 'from-amber-50/90 via-white to-orange-50/70',
    iconClass: 'bg-amber-500 text-white ring-amber-200 shadow-amber-100',
    textClass: 'text-amber-700',
    rowClass: 'border-amber-100 bg-amber-50/80',
  },
  payable: {
    accentClass: 'from-rose-500 to-red-500',
    borderClass: 'border-rose-100',
    surfaceClass: 'from-rose-50/90 via-white to-red-50/70',
    iconClass: 'bg-rose-600 text-white ring-rose-200 shadow-rose-100',
    textClass: 'text-rose-700',
    rowClass: 'border-rose-100 bg-rose-50/80',
  },
  profit: {
    accentClass: 'from-violet-500 to-emerald-500',
    borderClass: 'border-violet-100',
    surfaceClass: 'from-violet-50/90 via-white to-emerald-50/70',
    iconClass: 'bg-violet-600 text-white ring-violet-200 shadow-violet-100',
    textClass: 'text-violet-700',
    rowClass: 'border-violet-100 bg-violet-50/80',
  },
  tickets: {
    accentClass: 'from-sky-500 to-blue-500',
    borderClass: 'border-sky-100',
    surfaceClass: 'from-sky-50/90 via-white to-blue-50/70',
    iconClass: 'bg-sky-600 text-white ring-sky-200 shadow-sky-100',
    textClass: 'text-sky-700',
    rowClass: 'border-sky-100 bg-sky-50/80',
  },
  visa: {
    accentClass: 'from-purple-500 to-indigo-500',
    borderClass: 'border-purple-100',
    surfaceClass: 'from-purple-50/90 via-white to-indigo-50/70',
    iconClass: 'bg-purple-600 text-white ring-purple-200 shadow-purple-100',
    textClass: 'text-purple-700',
    rowClass: 'border-purple-100 bg-purple-50/80',
  },
  umrah: {
    accentClass: 'from-emerald-500 to-cyan-500',
    borderClass: 'border-emerald-100',
    surfaceClass: 'from-emerald-50/90 via-white to-cyan-50/70',
    iconClass: 'bg-emerald-600 text-white ring-emerald-200 shadow-emerald-100',
    textClass: 'text-emerald-700',
    rowClass: 'border-emerald-100 bg-emerald-50/80',
  },
  hotels: {
    accentClass: 'from-amber-500 to-yellow-500',
    borderClass: 'border-amber-100',
    surfaceClass: 'from-amber-50/90 via-white to-yellow-50/70',
    iconClass: 'bg-amber-500 text-white ring-amber-200 shadow-amber-100',
    textClass: 'text-amber-700',
    rowClass: 'border-amber-100 bg-amber-50/80',
  },
  neutral: {
    accentClass: 'from-slate-500 to-slate-700',
    borderClass: 'border-slate-200',
    surfaceClass: 'from-slate-50 via-white to-slate-100',
    iconClass: 'bg-slate-700 text-white ring-slate-200 shadow-slate-100',
    textClass: 'text-slate-700',
    rowClass: 'border-slate-200 bg-slate-50',
  },
});

export const EMPTY_TRAVEL_DASHBOARD_SUMMARY = Object.freeze({
  totalBookings: 0,
  tickets: 0,
  visaCases: 0,
  umrahBookings: 0,
  hotelBookings: 0,
  upcomingDepartures: 0,
  totalSales: 0,
  received: 0,
  refundPaid: 0,
  netTravelRevenue: 0,
  netTravelCost: 0,
  customerDue: 0,
  customerCredit: 0,
  vendorPayable: 0,
  vendorCredit: 0,
  grossProfit: 0,
  travelExpenses: 0,
  netProfit: 0,
  vendorPayments: 0,
  vendorReturnCashReceived: 0,
  travelExpensePaid: 0,
  travelCashIn: 0,
  travelCashOut: 0,
  netTravelCashMovement: 0,
  cashInHand: 0,
  bankBalance: 0,
  cashAccounts: [],
  bankAccounts: [],
  pendingVisas: 0,
  missingDocuments: 0,
  upcomingTrips: 0,
  upcomingBookings: [],
});

export const travelSummaryCards = Object.freeze([
  {
    key: 'totalBookings',
    labelKey: 'travel.dashboard.cards.totalBookings',
    icon: FaClipboardList,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'bookings',
    route: '/travel/bookings',
    filter: {},
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.totalBookings',
  },
  {
    key: 'tickets',
    labelKey: 'travel.dashboard.cards.tickets',
    icon: FaTicketAlt,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'tickets',
    route: '/travel/bookings',
    filter: { serviceType: 'air_ticket' },
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.tickets',
  },
  {
    key: 'visaCases',
    labelKey: 'travel.dashboard.cards.visaCases',
    icon: FaPassport,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'visa',
    route: '/travel/bookings',
    filter: { serviceType: 'visit_visa' },
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.visaCases',
  },
  {
    key: 'umrahBookings',
    labelKey: 'travel.dashboard.cards.umrahBookings',
    icon: FaKaaba,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'umrah',
    route: '/travel/bookings',
    filter: { serviceType: 'umrah_package' },
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.umrahBookings',
  },
  {
    key: 'hotelBookings',
    labelKey: 'travel.dashboard.cards.hotelBookings',
    icon: FaHotel,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'hotels',
    route: '/travel/bookings',
    filter: { serviceType: 'hotel' },
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.hotelBookings',
  },
  {
    key: 'upcomingDepartures',
    labelKey: 'travel.dashboard.cards.upcomingDepartures',
    icon: FaPlaneDeparture,
    format: 'number',
    category: TRAVEL_CARD_CATEGORIES.OPERATIONAL,
    tone: 'bookings',
    route: '/travel/bookings',
    filter: { datePreset: 'upcoming' },
    permission: 'travel.bookings.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.upcomingDepartures',
  },
  {
    key: 'netTravelRevenue',
    labelKey: 'travel.dashboard.cards.totalSales',
    icon: FaFileInvoiceDollar,
    format: 'currency',
    category: TRAVEL_CARD_CATEGORIES.FINANCIAL,
    tone: 'sales',
    route: '/travel/reports',
    filter: { view: 'sales' },
    permission: 'travel.reports',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.netTravelRevenue',
  },
  {
    key: 'received',
    labelKey: 'travel.dashboard.cards.received',
    icon: FaMoneyBillWave,
    format: 'currency',
    category: TRAVEL_CARD_CATEGORIES.FINANCIAL,
    tone: 'received',
    route: '/travel/payments/received',
    filter: {},
    anyPermissions: ['travel.bookings.view', 'travel.bookings.edit', 'travel.payments'],
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.received',
  },
  {
    key: 'customerDue',
    labelKey: 'travel.dashboard.cards.customerDue',
    icon: FaUsers,
    format: 'currency',
    category: TRAVEL_CARD_CATEGORIES.FINANCIAL,
    tone: 'due',
    route: '/travel/customers',
    filter: { balance: 'due', sort: 'balance_desc' },
    anyPermissions: ['travel.bookings.view', 'travel.customers', 'travel.payments'],
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.customerDue',
  },
  {
    key: 'vendorPayable',
    labelKey: 'travel.dashboard.cards.vendorPayable',
    icon: FaReceipt,
    format: 'currency',
    category: TRAVEL_CARD_CATEGORIES.FINANCIAL,
    tone: 'payable',
    route: '/travel/vendors',
    filter: { balance: 'payable', sort: 'balance_desc' },
    permission: 'travel.vendors.view',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.vendorPayable',
  },
  {
    key: 'netProfit',
    labelKey: 'travel.dashboard.cards.netProfit',
    icon: FaChartLine,
    format: 'currency',
    category: TRAVEL_CARD_CATEGORIES.FINANCIAL,
    tone: 'profit',
    route: '/travel/reports',
    filter: {},
    permission: 'travel.reports',
    module: MODULE_KEYS.TRAVEL,
    disabled: false,
    futureSource: 'travel-dashboard-summary.netProfit',
  },
]);

export const travelOperationalSummaryCards = Object.freeze(
  travelSummaryCards.filter((card) => card.category === TRAVEL_CARD_CATEGORIES.OPERATIONAL)
);

export const travelFinancialSummaryCards = Object.freeze(
  travelSummaryCards.filter((card) => card.category === TRAVEL_CARD_CATEGORIES.FINANCIAL)
);

export const travelQuickActions = Object.freeze([
  {
    key: 'newBooking',
    labelKey: 'travel.dashboard.actions.newBooking',
    icon: FaPlaneDeparture,
    tone: 'bookings',
    route: '/travel/bookings/new',
    permission: 'travel.bookings.create',
    disabled: false,
  },
  {
    key: 'receivePayment',
    labelKey: 'travel.dashboard.actions.receivePayment',
    icon: FaMoneyBillWave,
    tone: 'received',
    route: '/travel/payments/receive',
    anyPermissions: ['travel.bookings.view', 'travel.bookings.edit', 'travel.payments'],
    disabled: false,
  },
  {
    key: 'newRefund',
    labelKey: 'travel.dashboard.actions.newRefund',
    icon: FaUndo,
    tone: 'due',
    route: '/travel/refunds/new',
    permission: 'travel.bookings.edit',
    disabled: false,
  },
  {
    key: 'vendorPayment',
    labelKey: 'travel.dashboard.actions.vendorPayment',
    icon: FaShoppingBag,
    tone: 'payable',
    route: '/travel/vendor-payments/new',
    anyPermissions: ['travel.vendors.view', 'travel.vendors.manage', 'travel.payments'],
    disabled: false,
  },
  {
    key: 'addExpense',
    labelKey: 'travel.dashboard.actions.addExpense',
    icon: FaPlusCircle,
    tone: 'profit',
    route: '/travel/expenses/new',
    permission: 'expenses.create',
    disabled: false,
  },
]);

export const travelSecondaryPanels = Object.freeze([
  {
    key: 'pendingWork',
    titleKey: 'travel.dashboard.sections.pendingWork',
    icon: FaTasks,
    tone: 'visa',
    type: 'metrics',
    actionLabelKey: 'travel.dashboard.actions.viewPendingWork',
    route: '/travel/bookings',
    filter: { status: 'processing' },
    items: [
      {
        key: 'pendingVisas',
        labelKey: 'travel.dashboard.metrics.pendingVisas',
        format: 'number',
        icon: FaPassport,
        tone: 'visa',
        route: '/travel/bookings',
        filter: { serviceType: 'visit_visa', status: 'processing' },
      },
      {
        key: 'customerDue',
        labelKey: 'travel.dashboard.cards.customerDue',
        format: 'currency',
        icon: FaUsers,
        tone: 'due',
        route: '/travel/customers',
        filter: { balance: 'due', sort: 'balance_desc' },
      },
      {
        key: 'vendorPayable',
        labelKey: 'travel.dashboard.cards.vendorPayable',
        format: 'currency',
        icon: FaReceipt,
        tone: 'payable',
        route: '/travel/vendors',
        filter: { balance: 'payable', sort: 'balance_desc' },
      },
    ],
  },
  {
    key: 'upcomingTravel',
    titleKey: 'travel.dashboard.sections.upcomingTravel',
    icon: FaCalendarCheck,
    tone: 'tickets',
    type: 'upcoming',
    listKey: 'upcomingBookings',
    emptyKey: 'travel.dashboard.empty.noUpcomingTravel',
    actionLabelKey: 'travel.dashboard.actions.viewUpcoming',
    route: '/travel/bookings',
    filter: { datePreset: 'upcoming' },
  },
]);

export const travelRightPanelSections = Object.freeze([
  {
    key: 'balances',
    titleKey: 'travel.dashboard.panel.balances',
    icon: FaReceipt,
    tone: 'due',
    items: [
      {
        key: 'customerDue',
        labelKey: 'travel.dashboard.cards.customerDue',
        format: 'currency',
        icon: FaUsers,
        tone: 'due',
        route: '/travel/customers',
        filter: { balance: 'due', sort: 'balance_desc' },
      },
      {
        key: 'vendorPayable',
        labelKey: 'travel.dashboard.cards.vendorPayable',
        format: 'currency',
        icon: FaReceipt,
        tone: 'payable',
        route: '/travel/vendors',
        filter: { balance: 'payable', sort: 'balance_desc' },
      },
    ],
  },
  {
    key: 'financialPosition',
    titleKey: 'travel.dashboard.panel.financialPosition',
    icon: FaMoneyBillWave,
    tone: 'received',
    items: [
      {
        key: 'cashInHand',
        labelKey: 'travel.dashboard.metrics.cashInHand',
        format: 'currency',
        icon: FaMoneyBillWave,
        tone: 'received',
        route: '/travel/accounts/cash',
        filter: { moduleScope: 'travel' },
      },
      {
        key: 'bankBalance',
        labelKey: 'travel.dashboard.metrics.bankBalance',
        format: 'currency',
        icon: FaFileInvoiceDollar,
        tone: 'sales',
        route: '/travel/accounts/bank',
        filter: { moduleScope: 'travel' },
      },
    ],
    accountGroups: [
      {
        key: 'bankAccounts',
        titleKey: 'travel.dashboard.panel.bankAccounts',
        route: '/travel/accounts/bank',
      },
    ],
  },
  {
    key: 'attention',
    titleKey: 'travel.dashboard.panel.attention',
    icon: FaExclamationTriangle,
    tone: 'visa',
    items: [
      {
        key: 'pendingVisas',
        labelKey: 'travel.dashboard.metrics.pendingVisas',
        format: 'number',
        icon: FaPassport,
        tone: 'visa',
        route: '/travel/bookings',
        filter: { serviceType: 'visit_visa', status: 'processing' },
      },
    ],
  },
]);
