const WeavingContract = require("../models/WeavingContract");
const WeavingGodown = require("../models/WeavingGodown");
const WeavingParty = require("../models/WeavingParty");
const WeavingSizingBill = require("../models/WeavingSizingBill");
const WeavingSizingIssue = require("../models/WeavingSizingIssue");
const WeavingSizingReceipt = require("../models/WeavingSizingReceipt");
const WeavingYarn = require("../models/WeavingYarn");
const { logActivity } = require("../utils/activityLogger");
const commercial = require("../services/weaving/weavingCommercialService");
const sizing = require("../services/weaving/weavingSizingService");

const uid = (req) => req.user?.id || req.userId;
const fail = (res, error, message) => res.status(error.statusCode || 500).json({ message: error.message || message });
const respond = (res, promise, message) => promise.then((data) => res.json({ data })).catch((error) => fail(res, error, message));

exports.meta = async (req, res) => { try { const userId = uid(req); const [parties, yarns, godowns, contracts, issues, receipts] = await Promise.all([WeavingParty.find({ userId, isActive: true, isHidden: { $ne: true }, serviceTypes: "sizing" }).sort({ name: 1 }), WeavingYarn.find({ userId, isActive: true }).sort({ name: 1 }), WeavingGodown.find({ userId, isActive: true }).sort({ name: 1 }), WeavingContract.find({ userId }).sort({ contractDate: -1 }), WeavingSizingIssue.find({ userId, status: "posted" }).populate("sizingPartyId", "name").sort({ date: -1 }), WeavingSizingReceipt.find({ userId, status: "posted" }).populate("sizingPartyId", "name").sort({ date: -1 })]); return res.json({ data: { parties, yarns, godowns, contracts, issues, receipts, nextIssueNo: await commercial.nextNo(WeavingSizingIssue, userId, "issueNo", "SI"), nextReceiptNo: await commercial.nextNo(WeavingSizingReceipt, userId, "receiptNo", "SR"), nextBillNo: await commercial.nextNo(WeavingSizingBill, userId, "billNo", "SB") } }); } catch (error) { return fail(res, error, "Failed to load Sizing setup"); } };
exports.listIssues = (req, res) => respond(res, WeavingSizingIssue.find({ userId: uid(req), status: { $ne: "void" } }).populate("sizingPartyId", "name").populate("lines.yarnId", "name count").sort({ date: -1 }), "Failed to load issues");
exports.createIssue = async (req, res) => { try { const row = await sizing.createIssue(uid(req), req.body); await logActivity({ req, action: "create", module: "weaving.sizing.issue", moduleScope: "weaving", entityType: "WeavingSizingIssue", entityId: row._id, title: row.issueNo }); return res.status(201).json({ data: row }); } catch (error) { return fail(res, error, "Failed to create issue"); } };
exports.listReceipts = (req, res) => respond(res, WeavingSizingReceipt.find({ userId: uid(req), status: { $ne: "void" } }).populate("sizingPartyId", "name").populate("issueId", "issueNo").sort({ date: -1 }), "Failed to load receipts");
exports.createReceipt = async (req, res) => { try { const row = await sizing.createReceipt(uid(req), req.body); await logActivity({ req, action: "create", module: "weaving.sizing.receipt", moduleScope: "weaving", entityType: "WeavingSizingReceipt", entityId: row._id, title: row.receiptNo }); return res.status(201).json({ data: row }); } catch (error) { return fail(res, error, "Failed to create receipt"); } };
exports.createReturn = async (req, res) => { try { const row = await sizing.createReturn(uid(req), req.body); await logActivity({ req, action: "create", module: "weaving.sizing.return", moduleScope: "weaving", entityType: "WeavingYarnMovement", entityId: row._id, title: row.returnNo || "Sizing Yarn Return" }); return res.status(201).json({ data: row }); } catch (error) { return fail(res, error, "Failed to create Sizing return"); } };
exports.listBills = (req, res) => respond(res, WeavingSizingBill.find({ userId: uid(req), status: { $ne: "void" } }).populate("sizingPartyId", "name").populate("receiptId", "receiptNo").sort({ billDate: -1 }), "Failed to load bills");
exports.getBill = async (req, res) => { try { const row = await WeavingSizingBill.findOne({ _id: req.params.id, userId: uid(req) }).populate("sizingPartyId", "name phone").populate("receiptId", "receiptNo date").lean(); if (!row) return res.status(404).json({ message: "Sizing bill not found" }); return res.json({ data: row }); } catch (error) { return fail(res, error, "Failed to load Sizing bill"); } };
exports.createBill = async (req, res) => { try { const row = await sizing.createBill(uid(req), req.body); await logActivity({ req, action: "create", module: "weaving.sizing.bill", moduleScope: "weaving", entityType: "WeavingSizingBill", entityId: row._id, title: row.billNo }); return res.status(201).json({ data: row }); } catch (error) { return fail(res, error, "Failed to create bill"); } };
exports.materialLedger = (req, res) => respond(res, sizing.materialLedger(uid(req), req.query), "Failed to load material ledger");
exports.stock = async (req, res) => { try { const rows = await sizing.materialLedger(uid(req), req.query); const grouped = new Map(); rows.forEach((row) => { const key = `${row.sizingPartyId?._id}:${row.yarnId?._id}:${row.ownershipType}:${row.ownerPartyId?._id || "own"}`; grouped.set(key, { sizingParty: row.sizingPartyId, yarn: row.yarnId, ownershipType: row.ownershipType, owner: row.ownerPartyId, packageType: row.packageType, balanceKg: row.balanceKg, balancePackages: row.balancePackages, balanceSmallCones: row.balanceSmallCones, balanceLargeCones: row.balanceLargeCones }); }); return res.json({ data: [...grouped.values()].filter((row) => Math.abs(row.balanceKg) > 0.0001 || row.balancePackages || row.balanceSmallCones || row.balanceLargeCones) }); } catch (error) { return fail(res, error, "Failed to load Sizing stock"); } };
