const express = require("express");
const ctrl = require("../controllers/weavingSalesController");
const protect = require("../middleware/authMiddleware");
const { requireModule } = require("../middleware/moduleMiddleware");
const { requirePermission } = require("../middleware/permissionMiddleware");
const { MODULE_KEYS } = require("../utils/moduleConfig");
const router = express.Router();
const outputAuth = (req, res, next) => { if (req.query.token && !req.headers.authorization) req.headers.authorization = `Bearer ${req.query.token}`; next(); };
router.get("/invoices/:id/print", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.format = "print"; return ctrl.output(req, res); });
router.get("/invoices/:id/pdf", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.format = "pdf"; return ctrl.output(req, res); });
router.get("/kacchi/:id/print", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.kind = "kacchi"; req.params.format = "print"; return ctrl.parchiOutput(req, res); });
router.get("/kacchi/:id/pdf", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.kind = "kacchi"; req.params.format = "pdf"; return ctrl.parchiOutput(req, res); });
router.get("/pakki/:id/print", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.kind = "pakki"; req.params.format = "print"; return ctrl.parchiOutput(req, res); });
router.get("/pakki/:id/pdf", outputAuth, protect, requireModule(MODULE_KEYS.WEAVING), requirePermission("weaving.sales.print"), (req, res) => { req.params.kind = "pakki"; req.params.format = "pdf"; return ctrl.parchiOutput(req, res); });
router.use(protect, requireModule(MODULE_KEYS.WEAVING));
router.get("/workspace", requirePermission("weaving.sales.view", "weaving.rejection_return.view"), ctrl.workspace);
router.get("/invoices/:id", requirePermission("weaving.sales.view"), ctrl.getInvoice);
router.post("/kacchi", requirePermission("weaving.sales.create"), ctrl.createKacchi);
router.put("/kacchi/:id", requirePermission("weaving.sales.edit"), ctrl.updateKacchi);
router.post("/kacchi/:id/void", requirePermission("weaving.sales.void"), ctrl.voidKacchi);
router.post("/pakki", requirePermission("weaving.sales.create"), ctrl.createPakki);
router.post("/pakki/:id/void", requirePermission("weaving.sales.void"), ctrl.voidPakki);
router.post("/pakki/:pakkiId/invoice", requirePermission("weaving.sales.create"), ctrl.draftFromPakki);
router.post("/invoices/direct", requirePermission("weaving.sales.create"), ctrl.createDirect);
router.put("/invoices/:id", requirePermission("weaving.sales.edit"), ctrl.updateDraft);
router.post("/invoices/:id/post", requirePermission("weaving.sales.post"), ctrl.post);
router.post("/invoices/:id/void", requirePermission("weaving.sales.void"), ctrl.void);
router.post("/rejections/:dueId/receive", requirePermission("weaving.rejection_return.receive"), ctrl.receiveRejection);
router.post("/rejection-receipts/:id/reverse", requirePermission("weaving.rejection_return.reverse"), ctrl.reverseRejection);
module.exports = router;
