const express = require("express");
const ctrl = require("../controllers/weavingOperationsController");
const protect = require("../middleware/authMiddleware");
const { requireModule } = require("../middleware/moduleMiddleware");
const { requirePermission } = require("../middleware/permissionMiddleware");
const { MODULE_KEYS } = require("../utils/moduleConfig");
const { PERMISSIONS } = require("../utils/permissionList");

const router = express.Router();
router.use(protect, requireModule(MODULE_KEYS.WEAVING));
router.get("/master-options", requirePermission(PERMISSIONS.WEAVING_MASTERS.VIEW), ctrl.listMasterOptions);
router.post("/master-options", requirePermission(PERMISSIONS.WEAVING_MASTERS.CREATE), ctrl.quickAddMasterOption);
router.get("/masters/:kind", requirePermission(PERMISSIONS.WEAVING_MASTERS.VIEW), ctrl.listMaster);
router.post("/masters/:kind", requirePermission(PERMISSIONS.WEAVING_MASTERS.CREATE), ctrl.createMaster);
router.put("/masters/:kind/:id", requirePermission(PERMISSIONS.WEAVING_MASTERS.EDIT), ctrl.updateMaster);
router.get("/looms", requirePermission(PERMISSIONS.WEAVING_MASTERS.VIEW), ctrl.listLooms);
router.post("/looms", requirePermission(PERMISSIONS.WEAVING_MASTERS.CREATE), ctrl.createLoom);
router.post("/looms/bulk", requirePermission(PERMISSIONS.WEAVING_MASTERS.CREATE), ctrl.bulkCreateLooms);
router.put("/looms/:id", requirePermission(PERMISSIONS.WEAVING_MASTERS.EDIT), ctrl.updateLoom);
router.get("/godowns", requirePermission(PERMISSIONS.WEAVING_SETTINGS.MANAGE, PERMISSIONS.WEAVING_MASTERS.VIEW, PERMISSIONS.WEAVING_CONTRACTS.VIEW), ctrl.listGodowns);
router.post("/godowns", requirePermission(PERMISSIONS.WEAVING_SETTINGS.MANAGE), ctrl.createGodown);
router.put("/godowns/:id", requirePermission(PERMISSIONS.WEAVING_SETTINGS.MANAGE), ctrl.updateGodown);
router.get("/parties", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.VIEW), ctrl.listParties);
router.post("/parties", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.CREATE), ctrl.createParty);
router.get("/contracts/meta", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.VIEW), ctrl.contractMeta);
router.get("/contracts", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.VIEW), ctrl.listContracts);
router.post("/contracts", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.CREATE), ctrl.createContract);
router.put("/contracts/:id", requirePermission(PERMISSIONS.WEAVING_CONTRACTS.EDIT), ctrl.updateContract);
module.exports = router;
