const express = require("express");
const ctrl = require("../controllers/weavingCommercialController");
const weavingLedgerPrint = require("../controllers/weavingLedgerPrintController");
const sizing = require("../controllers/weavingSizingController");
const protect = require("../middleware/authMiddleware");
const { requireModule } = require("../middleware/moduleMiddleware");
const { requirePermission } = require("../middleware/permissionMiddleware");
const { MODULE_KEYS } = require("../utils/moduleConfig");
const upload = require("../middleware/uploadMiddleware");
const router = express.Router();
router.use(protect, requireModule(MODULE_KEYS.WEAVING));
router.get("/parties", requirePermission("weaving.counterparties.view"), ctrl.listParties);
router.post("/parties", requirePermission("weaving.counterparties.create"), ctrl.createParty);
router.put("/parties/:id", requirePermission("weaving.counterparties.edit"), ctrl.updateParty);
router.patch("/parties/:id/hide", requirePermission("weaving.counterparties.hide"), ctrl.hideParty);
router.patch("/parties/:id/restore", requirePermission("weaving.counterparties.restore"), ctrl.restoreParty);
router.post("/parties/merge/confirm", requirePermission("weaving.counterparties.merge"), ctrl.mergeParties);
router.get("/parties/:id/ledger", requirePermission("weaving.counterparties.view_ledger"), ctrl.partyLedger);
router.get("/parties/:id/ledger/print", requirePermission("weaving.counterparties.view_ledger"), (req, res) => { req.params.format = "print"; return weavingLedgerPrint.partyLedgerOutput(req, res); });
router.get("/parties/:id/ledger/pdf", requirePermission("weaving.counterparties.view_ledger"), (req, res) => { req.params.format = "pdf"; return weavingLedgerPrint.partyLedgerOutput(req, res); });
router.get("/parties/:id/balance", requirePermission("weaving.counterparties.view"), ctrl.getPartyBalance);
router.get("/outstanding", requirePermission("weaving.counterparties.view"), ctrl.outstanding);
router.get("/meta/versions", requirePermission("weaving.purchases.view", "weaving.payments.view"), ctrl.metaVersions);
router.get("/meta", requirePermission("weaving.purchases.view", "weaving.payments.view"), ctrl.meta);
router.post("/items", requirePermission("weaving.purchases.create"), ctrl.createItem);
router.get("/purchases", requirePermission("weaving.purchases.view"), ctrl.listPurchases);
router.get("/purchases/:id", requirePermission("weaving.purchases.view"), ctrl.getPurchase);
router.post("/purchases", requirePermission("weaving.purchases.create"), upload.array("attachments", 3), ctrl.createPurchase);
router.put("/purchases/:id", requirePermission("weaving.purchases.edit"), upload.array("attachments", 3), ctrl.updatePurchase);
router.post("/purchases/:id/void", requirePermission("weaving.purchases.void"), ctrl.voidPurchase);
router.get("/purchase-history", requirePermission("weaving.purchases.view"), ctrl.purchaseHistory);
router.get("/payments", requirePermission("weaving.payments.view"), ctrl.listPayments);
router.get("/payments/:id", requirePermission("weaving.payments.view"), ctrl.getPayment);
router.post("/payments", requirePermission("weaving.payments.create"), upload.array("attachments", 3), ctrl.returnExistingPayment, ctrl.createPayment);
router.get("/sizing/meta", requirePermission("weaving.sizing.view"), sizing.meta);
router.get("/sizing/issues", requirePermission("weaving.sizing.view"), sizing.listIssues);
router.post("/sizing/issues", requirePermission("weaving.sizing.issue"), sizing.createIssue);
router.get("/sizing/receipts", requirePermission("weaving.sizing.view"), sizing.listReceipts);
router.post("/sizing/receipts", requirePermission("weaving.sizing.receive"), sizing.createReceipt);
router.post("/sizing/returns", requirePermission("weaving.sizing.receive"), sizing.createReturn);
router.get("/sizing/bills", requirePermission("weaving.sizing.view"), sizing.listBills);
router.get("/sizing/bills/:id", requirePermission("weaving.sizing.view"), sizing.getBill);
router.post("/sizing/bills", requirePermission("weaving.sizing.bill"), sizing.createBill);
router.get("/sizing/material-ledger", requirePermission("weaving.sizing.view_material_ledger"), sizing.materialLedger);
router.get("/sizing/stock", requirePermission("weaving.sizing.view_material_ledger"), sizing.stock);
router.get("/journals/:id", requirePermission("weaving.counterparties.view_ledger"), ctrl.getJournal);
module.exports = router;
