import {
  FaCalendarCheck,
  FaChartLine,
  FaCheckCircle,
  FaClipboardList,
  FaCubes,
  FaFileInvoiceDollar,
  FaIndustry,
  FaMoneyBillWave,
  FaReceipt,
  FaRulerCombined,
  FaShoppingCart,
  FaUniversity,
} from 'react-icons/fa';

export const EMPTY_WEAVING_DASHBOARD_SUMMARY = Object.freeze({
  masterForms: null,
  looms: null,
  netProfit: null,
  totalExpenses: null,
  attendance: null,
  productionMeters: null,
  salesRevenue: null,
  purchaseTotal: null,
  readyToInvoice: null,
  pendingRejectionMeter: null,
  payrollDue: null,
  employeeFinanceOutstanding: null,
  sizingPending: null,
  stockSummary: null,
  receivable: null,
  payable: null,
  partyReceivable: null,
  partyPayable: null,
  employeeRecoverable: null,
  employeePayable: null,
  cashInHand: null,
  bankBalance: null,
  sizingStockKg: null,
  fabricStockMeter: null,
  salaryDue: null,
  partyReceivableDetails: [],
  partyPayableDetails: [],
  receivableDetails: [],
  payableDetails: [],
  cashAccounts: [],
  bankAccounts: [],
});

export const weavingToneClasses = Object.freeze({
  profit: {
    accentClass: 'from-indigo-500 to-emerald-500',
    borderClass: 'border-indigo-100',
    surfaceClass: 'from-indigo-50/90 via-white to-emerald-50/70',
    iconClass: 'bg-indigo-700 text-white ring-indigo-200 shadow-indigo-100',
    textClass: 'text-indigo-700',
    rowClass: 'border-indigo-100 bg-indigo-50/80',
  },
  expense: {
    accentClass: 'from-rose-500 to-slate-600',
    borderClass: 'border-rose-100',
    surfaceClass: 'from-rose-50/90 via-white to-slate-50',
    iconClass: 'bg-rose-600 text-white ring-rose-200 shadow-rose-100',
    textClass: 'text-rose-700',
    rowClass: 'border-rose-100 bg-rose-50/80',
  },
  production: {
    accentClass: 'from-slate-600 to-teal-500',
    borderClass: 'border-slate-200',
    surfaceClass: 'from-slate-50 via-white to-teal-50/80',
    iconClass: 'bg-slate-800 text-white ring-slate-200 shadow-slate-100',
    textClass: 'text-slate-700',
    rowClass: 'border-slate-200 bg-slate-50',
  },
  payroll: {
    accentClass: 'from-emerald-500 to-teal-500',
    borderClass: 'border-emerald-100',
    surfaceClass: 'from-emerald-50/90 via-white to-teal-50/70',
    iconClass: 'bg-emerald-600 text-white ring-emerald-200 shadow-emerald-100',
    textClass: 'text-emerald-700',
    rowClass: 'border-emerald-100 bg-emerald-50/80',
  },
  finance: {
    accentClass: 'from-amber-500 to-cyan-600',
    borderClass: 'border-amber-100',
    surfaceClass: 'from-amber-50/90 via-white to-cyan-50/70',
    iconClass: 'bg-amber-600 text-white ring-amber-200 shadow-amber-100',
    textClass: 'text-amber-700',
    rowClass: 'border-amber-100 bg-amber-50/80',
  },
  sizing: {
    accentClass: 'from-cyan-500 to-indigo-500',
    borderClass: 'border-cyan-100',
    surfaceClass: 'from-cyan-50/90 via-white to-indigo-50/70',
    iconClass: 'bg-cyan-700 text-white ring-cyan-200 shadow-cyan-100',
    textClass: 'text-cyan-700',
    rowClass: 'border-cyan-100 bg-cyan-50/80',
  },
  stock: {
    accentClass: 'from-teal-500 to-slate-600',
    borderClass: 'border-teal-100',
    surfaceClass: 'from-teal-50/90 via-white to-slate-50',
    iconClass: 'bg-teal-700 text-white ring-teal-200 shadow-teal-100',
    textClass: 'text-teal-700',
    rowClass: 'border-teal-100 bg-teal-50/80',
  },
  attendance: {
    accentClass: 'from-cyan-500 to-emerald-500',
    borderClass: 'border-cyan-100',
    surfaceClass: 'from-cyan-50/90 via-white to-emerald-50/70',
    iconClass: 'bg-cyan-700 text-white ring-cyan-200 shadow-cyan-100',
    textClass: 'text-cyan-700',
    rowClass: 'border-cyan-100 bg-cyan-50/80',
  },
});

export const weavingDashboardCards = Object.freeze([
  {
    key: 'masterForms',
    labelKey: 'weaving.dashboard.cards.masterForms',
    displayValueKey: 'weaving.nav.allMasterForms',
    icon: FaClipboardList,
    tone: 'production',
    route: '/weaving/forms',
    anyPermissions: ['weaving.masters.view', 'weaving.contracts.view'],
  },
  {
    key: 'looms',
    labelKey: 'weaving.dashboard.cards.looms',
    icon: FaIndustry,
    format: 'looms',
    tone: 'production',
    route: '/weaving/forms?tab=loom',
    permission: 'weaving.masters.view',
  },
  {
    key: 'netProfit',
    labelKey: 'weaving.dashboard.cards.profitLoss',
    icon: FaChartLine,
    format: 'profit',
    tone: 'profit',
    route: '/weaving/reports?tab=profit',
    permission: 'weaving.reports.profit',
    futureSource: 'weaving-dashboard-summary.netProfit',
  },
  {
    key: 'salesRevenue',
    labelKey: 'weaving.dashboard.cards.monthSales',
    icon: FaFileInvoiceDollar,
    format: 'currency',
    tone: 'finance',
    route: '/weaving/reports?tab=sales',
    anyPermissions: ['weaving.reports.view', 'weaving.reports.sales'],
    futureSource: 'weaving-dashboard-summary.salesRevenue',
  },
  {
    key: 'productionMeters',
    labelKey: 'weaving.dashboard.cards.production',
    icon: FaIndustry,
    format: 'meters',
    tone: 'production',
    route: '/weaving/production',
    anyPermissions: ['weaving.reports.view', 'weaving.reports.production'],
    futureSource: 'weaving-dashboard-summary.productionMeters',
  },
  {
    key: 'totalExpenses',
    labelKey: 'weaving.dashboard.cards.expenses',
    icon: FaReceipt,
    format: 'currency',
    tone: 'expense',
    route: '/weaving/expenses',
    permission: 'expenses.view',
    futureSource: 'weaving-dashboard-summary.totalExpenses',
  },
  {
    key: 'payrollDue',
    labelKey: 'weaving.dashboard.cards.salaryPayroll',
    icon: FaMoneyBillWave,
    format: 'currency',
    tone: 'payroll',
    route: '/weaving/payroll',
    anyPermissions: ['payroll.view', 'payroll.create', 'payroll.edit', 'payroll.pay'],
    futureSource: 'weaving-dashboard-summary.payrollDue',
  },
  {
    key: 'purchaseTotal',
    labelKey: 'weaving.dashboard.cards.monthPurchases',
    icon: FaShoppingCart,
    format: 'currency',
    tone: 'stock',
    route: '/weaving/purchase',
    permission: 'weaving.purchases.view',
    futureSource: 'weaving-dashboard-summary.purchaseTotal',
  },
  {
    key: 'readyToInvoice',
    labelKey: 'weaving.dashboard.cards.readyToInvoice',
    icon: FaCheckCircle,
    format: 'number',
    tone: 'payroll',
    route: '/weaving/sales-settlement?tab=ready',
    permission: 'weaving.sales.view',
    futureSource: 'weaving-dashboard-summary.readyToInvoice',
  },
  {
    key: 'pendingRejectionMeter',
    labelKey: 'weaving.dashboard.cards.pendingRejection',
    icon: FaReceipt,
    format: 'meters',
    tone: 'expense',
    route: '/weaving/reports?tab=rejection',
    anyPermissions: ['weaving.reports.view', 'weaving.reports.sales'],
    futureSource: 'weaving-dashboard-summary.pendingRejectionMeter',
  },
  {
    key: 'attendance',
    labelKey: 'weaving.dashboard.cards.attendance',
    icon: FaCalendarCheck,
    format: 'attendance',
    tone: 'attendance',
    route: '/weaving/attendance',
    anyPermissions: ['weaving.attendance.view', 'weaving.attendance.manage', 'weaving.attendance.override'],
    futureSource: 'weaving-dashboard-summary.attendance',
  },
  {
    key: 'stockSummary',
    labelKey: 'weaving.dashboard.cards.stock',
    icon: FaCubes,
    format: 'number',
    tone: 'stock',
    route: '/weaving/yarn-stock',
    permission: 'weaving.yarn_stock.view',
    futureSource: 'weaving-dashboard-summary.stockSummary',
  },
]);

export const weavingRightPanelSections = Object.freeze([
  {
    key: 'balances',
    titleKey: 'weaving.panel.balances',
    icon: FaReceipt,
    tone: 'expense',
    items: [
      {
        key: 'receivable',
        labelKey: 'weaving.panel.receivable',
        format: 'currency',
        icon: FaChartLine,
        tone: 'profit',
        breakdownType: 'receivable',
        anyPermissions: ['weaving.counterparties.view', 'payroll.view'],
      },
      {
        key: 'payable',
        labelKey: 'weaving.panel.payable',
        format: 'currency',
        icon: FaReceipt,
        tone: 'expense',
        breakdownType: 'payable',
        anyPermissions: ['weaving.counterparties.view', 'payroll.view'],
      },
    ],
  },
  {
    key: 'financialPosition',
    titleKey: 'weaving.panel.financialPosition',
    icon: FaMoneyBillWave,
    tone: 'finance',
    items: [
      {
        key: 'cashInHand',
        labelKey: 'weaving.panel.handCash',
        format: 'currency',
        icon: FaMoneyBillWave,
        tone: 'payroll',
        route: '/weaving/accounts/cash',
        filter: { moduleScope: 'weaving' },
        permission: 'accounts.view',
      },
      {
        key: 'bankBalance',
        labelKey: 'weaving.panel.bank',
        format: 'currency',
        icon: FaUniversity,
        tone: 'production',
        route: '/weaving/accounts/bank',
        filter: { moduleScope: 'weaving' },
        permission: 'accounts.view',
      },
    ],
    accountGroups: [
      {
        key: 'cashAccounts',
        titleKey: 'weaving.panel.cashAccounts',
        route: '/weaving/accounts/cash',
        permission: 'accounts.view',
      },
      {
        key: 'bankAccounts',
        titleKey: 'weaving.panel.bankAccounts',
        route: '/weaving/accounts/bank',
        permission: 'accounts.view',
      },
    ],
  },
  {
    key: 'operations',
    titleKey: 'weaving.panel.operations',
    icon: FaIndustry,
    tone: 'production',
    items: [
      {
        key: 'productionMeters',
        labelKey: 'weaving.panel.production',
        format: 'meters',
        icon: FaIndustry,
        tone: 'production',
        route: '/weaving/production',
        anyPermissions: ['weaving.reports.view', 'weaving.reports.production'],
      },
      {
        key: 'sizingStockKg',
        labelKey: 'weaving.panel.sizing',
        format: 'kg',
        icon: FaRulerCombined,
        tone: 'sizing',
        route: '/weaving/sizing',
        permission: 'weaving.sizing.view_material_ledger',
      },
      {
        key: 'fabricStockMeter',
        labelKey: 'weaving.panel.stock',
        format: 'meters',
        icon: FaCubes,
        tone: 'stock',
        route: '/weaving/fabric-stock',
        permission: 'weaving.fabric_stock.view',
      },
    ],
  },
  {
    key: 'payroll',
    titleKey: 'weaving.panel.payroll',
    icon: FaMoneyBillWave,
    tone: 'payroll',
    items: [
      {
        key: 'salaryDue',
        labelKey: 'weaving.panel.salaryDue',
        format: 'currency',
        icon: FaMoneyBillWave,
        tone: 'payroll',
        route: '/weaving/payroll',
        permission: 'payroll.view',
      },
    ],
  },
]);
