import axios from 'axios';
import { commercialVersionsMatch, getCachedCommercialMeta, getCachedCommercialVersions, invalidateCommercialSections, setCachedCommercialMeta } from '../utils/weavingCommercialCache';
const URL = `${process.env.REACT_APP_API_BASE_URL}/api/weaving/commercial`;
const cfg = (params) => ({ headers: { Authorization: `Bearer ${localStorage.getItem('token')}` }, params });
const unwrap = (r) => r.data?.data ?? r.data;
let metaRequest = null;
const partyListRequests = new Map();
const ledgerRequests = new Map();
export const getCommercialMeta = async ({ force = false } = {}) => {
  if (metaRequest) return metaRequest;
  metaRequest = (async () => {
    const cached = getCachedCommercialMeta();
    const versions = unwrap(await axios.get(`${URL}/meta/versions`, cfg()));
    if (!force && cached && Array.isArray(cached.fabrics) && Array.isArray(cached.openSales) && commercialVersionsMatch(versions, getCachedCommercialVersions())) return cached;
    const data = unwrap(await axios.get(`${URL}/meta`, cfg()));
    setCachedCommercialMeta(data, versions);
    return data;
  })();
  try { return await metaRequest; } finally { metaRequest = null; }
};
export const listCounterparties = async (params = {}) => { const key = JSON.stringify(params); if (partyListRequests.has(key)) return partyListRequests.get(key); const request = axios.get(`${URL}/parties`, cfg(params)).then(unwrap); partyListRequests.set(key, request); try { return await request; } finally { partyListRequests.delete(key); } };
export const createCounterparty = async (body) => { const row = unwrap(await axios.post(`${URL}/parties`, body, cfg())); invalidateCommercialSections('parties'); return row; };
export const updateCounterparty = async (id, body) => { const row = unwrap(await axios.put(`${URL}/parties/${id}`, body, cfg())); invalidateCommercialSections('parties'); return row; };
export const hideCounterparty = async (id, reason = '') => { const row = unwrap(await axios.patch(`${URL}/parties/${id}/hide`, { reason }, cfg())); invalidateCommercialSections('parties'); return row; };
export const restoreCounterparty = async (id) => { const row = unwrap(await axios.patch(`${URL}/parties/${id}/restore`, {}, cfg())); invalidateCommercialSections('parties'); return row; };
export const mergeCounterparties = async (sourceId, targetId) => { const result = unwrap(await axios.post(`${URL}/parties/merge/confirm`, { sourceId, targetId }, cfg())); invalidateCommercialSections('parties'); return result; };
export const getCounterpartyLedger = async (id, params = {}) => { const key = `${id}:${JSON.stringify(params)}`; if (ledgerRequests.has(key)) return ledgerRequests.get(key); const request = axios.get(`${URL}/parties/${id}/ledger`, cfg(params)).then(unwrap); ledgerRequests.set(key, request); try { return await request; } finally { ledgerRequests.delete(key); } };
export const getCounterpartyLedgerOutputUrl = (id, format = 'pdf', params = {}) => { const query = new URLSearchParams(Object.entries(params).filter(([, value]) => value)); return `${URL}/parties/${id}/ledger/${format}${query.size ? `?${query}` : ''}`; };
export const openCounterpartyLedgerPrint = async (id, params = {}) => { const response = await axios.get(getCounterpartyLedgerOutputUrl(id, 'print', params), { ...cfg(), responseType: 'blob' }); const url = window.URL.createObjectURL(response.data); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => window.URL.revokeObjectURL(url), 60000); };
export const downloadCounterpartyLedgerPdf = async (id, params = {}) => { const response = await axios.get(getCounterpartyLedgerOutputUrl(id, 'pdf', params), { ...cfg(), responseType: 'blob' }); const url = window.URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `Weaving-Party-Ledger-${id}.pdf`; link.click(); window.URL.revokeObjectURL(url); };
export const getCounterpartyBalance = async (id) => unwrap(await axios.get(`${URL}/parties/${id}/balance`, cfg()));
export const getOutstanding = async () => unwrap(await axios.get(`${URL}/outstanding`, cfg()));
export const createWeavingItem = async (body) => { const row = unwrap(await axios.post(`${URL}/items`, body, cfg())); invalidateCommercialSections('items'); return row; };
export const listPurchases = async (params = {}) => unwrap(await axios.get(`${URL}/purchases`, cfg(params)));
export const getPurchaseById = async (id) => unwrap(await axios.get(`${URL}/purchases/${id}`, cfg()));
const multipart = (body) => { const data = new FormData(); Object.entries(body).forEach(([key, value]) => { if (key === 'attachments') (value || []).forEach((file) => data.append('attachments', file)); else data.append(key, typeof value === 'object' ? JSON.stringify(value) : value ?? ''); }); return data; };
export const createPurchase = async (body) => unwrap(await axios.post(`${URL}/purchases`, multipart(body), cfg()));
export const updatePurchase = async (id, body) => unwrap(await axios.put(`${URL}/purchases/${id}`, multipart(body), cfg()));
export const voidPurchase = async (id, reason) => unwrap(await axios.post(`${URL}/purchases/${id}/void`, { reason }, cfg()));
export const getPurchaseHistory = async (params) => unwrap(await axios.get(`${URL}/purchase-history`, cfg(params)));
export const listPayments = async (params = {}) => unwrap(await axios.get(`${URL}/payments`, cfg(params)));
export const getPaymentById = async (id) => unwrap(await axios.get(`${URL}/payments/${id}`, cfg()));
export const createMoneyTransaction = async (body) => unwrap(await axios.post(`${URL}/payments`, multipart(body), cfg()));
export const updateMoneyTransaction = async (id, body) => unwrap(await axios.put(`${URL}/payments/${id}`, multipart(body), cfg()));
export const voidMoneyTransaction = async (id, reason = '') => unwrap(await axios.post(`${URL}/payments/${id}/void`, { reason }, cfg()));
export const getSizingMeta = async () => unwrap(await axios.get(`${URL}/sizing/meta`, cfg()));
export const listSizingIssues = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/issues`, cfg(params)));
export const createSizingIssue = async (body) => unwrap(await axios.post(`${URL}/sizing/issues`, body, cfg()));
export const updateSizingIssue = async (id, body) => unwrap(await axios.put(`${URL}/sizing/issues/${id}`, body, cfg()));
export const voidSizingIssue = async (id, reason = '') => unwrap(await axios.post(`${URL}/sizing/issues/${id}/void`, { reason }, cfg()));
export const listSizingReceipts = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/receipts`, cfg(params)));
export const listSizingReturns = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/returns`, cfg(params)));
export const createSizingReceipt = async (body) => unwrap(await axios.post(`${URL}/sizing/receipts`, body, cfg()));
export const updateSizingReceipt = async (id, body) => unwrap(await axios.put(`${URL}/sizing/receipts/${id}`, body, cfg()));
export const voidSizingReceipt = async (id, reason = '') => unwrap(await axios.post(`${URL}/sizing/receipts/${id}/void`, { reason }, cfg()));
export const createSizingReturn = async (body) => unwrap(await axios.post(`${URL}/sizing/returns`, body, cfg()));
export const updateSizingReturn = async (id, body) => unwrap(await axios.put(`${URL}/sizing/returns/${id}`, body, cfg()));
export const voidSizingReturn = async (id, reason = '') => unwrap(await axios.post(`${URL}/sizing/returns/${id}/void`, { reason }, cfg()));
export const listSizingBills = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/bills`, cfg(params)));
export const getSizingBillById = async (id) => unwrap(await axios.get(`${URL}/sizing/bills/${id}`, cfg()));
export const createSizingBill = async (body) => unwrap(await axios.post(`${URL}/sizing/bills`, body, cfg()));
export const updateSizingBill = async (id, body) => unwrap(await axios.put(`${URL}/sizing/bills/${id}`, body, cfg()));
export const voidSizingBill = async (id, reason = '') => unwrap(await axios.post(`${URL}/sizing/bills/${id}/void`, { reason }, cfg()));
export const getSizingMaterialLedger = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/material-ledger`, cfg(params)));
export const getSizingStock = async (params = {}) => unwrap(await axios.get(`${URL}/sizing/stock`, cfg(params)));
export const getWeavingJournalById = async (id) => unwrap(await axios.get(`${URL}/journals/${id}`, cfg()));
