import React, { useEffect, useMemo, useState } from 'react';
import { FaTimes } from 'react-icons/fa';

import SearchableCreatableSelect from './SearchableCreatableSelect';
import { t } from '../../i18n/i18n';
import { getBusinessDateInputValue } from '../../utils/localDateTime';

const recoveryKey = 'weaving:sale:unsaved:direct';
const input = 'mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100 disabled:bg-slate-100';
const key = () => window.crypto?.randomUUID?.() || `${Date.now()}-${Math.random()}`;
const Field = ({ label, children, className = '' }) => <label className={`block text-sm font-medium text-slate-700 ${className}`}><span>{label}</span>{children}</label>;

const emptyForm = () => ({ invoiceNo: '', invoiceDate: getBusinessDateInputValue(), partyId: '', saleNature: 'fabric', fabricCategory: 'normal', otherSubtype: 'rejected', fabricQualityId: '', yarnId: '', godownId: '', description: '', quantity: '', uom: 'Job', weightKg: '', thanCount: '', pieceCount: '', finalRate: '', discountAmount: '', taxAmount: '', creditDays: '', saleTerms: 'credit', receivedNow: '', paymentAccountId: '', paymentMethod: 'cash', receiptRequestKey: key(), notes: '' });
const fromInvoice = (invoice) => ({ ...emptyForm(), invoiceNo: invoice.invoiceNo || '', invoiceDate: invoice.invoiceDate, partyId: invoice.partyId?._id || invoice.partyId || '', saleNature: invoice.saleNature, fabricCategory: invoice.fabricCategory || 'normal', otherSubtype: invoice.otherSubtype || 'rejected', fabricQualityId: invoice.fabricQualityId?._id || invoice.fabricQualityId || '', yarnId: invoice.yarnId?._id || invoice.yarnId || '', godownId: invoice.godownId?._id || invoice.godownId || '', description: invoice.description || '', quantity: invoice.quantity || '', uom: invoice.uom || 'Job', weightKg: invoice.weightKg || '', thanCount: invoice.thanCount || '', pieceCount: invoice.pieceCount || '', finalRate: invoice.finalRate || '', discountAmount: invoice.discountAmount || '', taxAmount: invoice.taxAmount || '', creditDays: invoice.creditDays || '', saleTerms: invoice.saleTerms || 'credit', receivedNow: invoice.receivedNowRequested || '', paymentAccountId: invoice.paymentAccountId || '', paymentMethod: invoice.paymentMethod || 'cash', receiptRequestKey: invoice.receiptRequestKey || key(), notes: invoice.notes || '' });
const restore = () => { try { return { ...emptyForm(), ...JSON.parse(localStorage.getItem(recoveryKey) || '{}') }; } catch { return emptyForm(); } };
export const clearDirectSaleRecovery = () => localStorage.removeItem(recoveryKey);

export default function WeavingDirectSaleModal({ meta, current, saving, onClose, onSave }) {
  const [form, setForm] = useState(() => current ? fromInvoice(current) : restore());
  const general = form.saleNature === 'other' && form.otherSubtype === 'other';
  const grand = useMemo(() => Math.max(0, Number(form.quantity || (general ? 1 : 0)) * Number(form.finalRate || 0) - Number(form.discountAmount || 0) + Number(form.taxAmount || 0)), [form.quantity, form.finalRate, form.discountAmount, form.taxAmount, general]);
  useEffect(() => { if (current) return undefined; const timer = window.setTimeout(() => localStorage.setItem(recoveryKey, JSON.stringify(form)), 250); return () => window.clearTimeout(timer); }, [current, form]);
  const patch = (next) => setForm((value) => ({ ...value, ...next }));
  useEffect(() => { if (!current && meta.nextInvoiceNo) setForm((value) => ({ ...value, invoiceNo: value.invoiceNo || meta.nextInvoiceNo })); }, [current, meta.nextInvoiceNo]);
  const close = () => { if (!current) clearDirectSaleRecovery(); onClose(); };
  const save = async () => { const result = await onSave({ ...form, quantity: form.quantity || (general ? 1 : ''), receivedNow: form.saleTerms === 'paid' ? grand : form.receivedNow }); if (result && !current) clearDirectSaleRecovery(); };
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/45 p-3"><section className="max-h-[94vh] w-full max-w-6xl overflow-y-auto rounded-md bg-white shadow-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-5 py-4"><h2 className="text-lg font-bold text-slate-900">{current ? `Edit ${current.invoiceNo}` : t('weaving.sales.newDirect')}</h2><button type="button" aria-label="Close" onClick={close} className="flex h-9 w-9 items-center justify-center rounded-md hover:bg-slate-100"><FaTimes /></button></header><div className="grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4">
    <Field label="Invoice No."><input disabled className={input} value={current?.invoiceNo || form.invoiceNo || meta.nextInvoiceNo || ''} /></Field>
    <Field label={t('weaving.sales.invoiceDate')}><input type="date" className={input} value={form.invoiceDate} onChange={(event) => patch({ invoiceDate: event.target.value })} /></Field>
    <SearchableCreatableSelect label={t('weaving.sales.party')} options={meta.parties.filter((row) => !row.serviceTypes?.includes('sizing') && (row.role === 'customer' || row.role === 'both'))} value={form.partyId} required onChange={(partyId) => patch({ partyId })} />
    <Field label={t('weaving.sales.saleType')}><select disabled={Boolean(current)} className={input} value={form.saleNature} onChange={(event) => patch({ saleNature: event.target.value, fabricQualityId: '', yarnId: '', godownId: '' })}><option value="fabric">{t('weaving.sales.fabricSale')}</option><option value="yarn">{t('weaving.sales.yarnSale')}</option><option value="other">{t('weaving.sales.otherSale')}</option></select></Field>
    {form.saleNature === 'fabric' && <Field label={t('weaving.sales.grade')}><select className={input} value={form.fabricCategory} onChange={(event) => patch({ fabricCategory: event.target.value })}><option value="normal">Normal / A</option><option value="b">B Grade</option></select></Field>}
    {form.saleNature === 'other' && <Field label={t('weaving.sales.subtype')}><select disabled={Boolean(current)} className={input} value={form.otherSubtype} onChange={(event) => patch({ otherSubtype: event.target.value })}><option value="rejected">{t('weaving.sales.rejected')}</option><option value="cut_piece">{t('weaving.sales.cutPiece')}</option><option value="waste">{t('weaving.sales.waste')}</option><option value="other">{t('weaving.sales.generalOther')}</option></select></Field>}
    {!general && form.saleNature !== 'yarn' && <SearchableCreatableSelect label={t('weaving.sales.quality')} options={meta.qualities} value={form.fabricQualityId} required onChange={(fabricQualityId) => patch({ fabricQualityId })} />}
    {form.saleNature === 'yarn' && <SearchableCreatableSelect label={t('weaving.sales.yarn')} options={meta.yarns} value={form.yarnId} required onChange={(yarnId) => patch({ yarnId })} />}
    {!general && <Field label={t('weaving.sales.godown')}><select className={input} value={form.godownId} onChange={(event) => patch({ godownId: event.target.value })}><option value="">Select Godown</option>{meta.godowns.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select></Field>}
    {general && <><Field label={t('weaving.sales.description')} className="lg:col-span-2"><input className={input} value={form.description} onChange={(event) => patch({ description: event.target.value })} /></Field><Field label="UOM"><select className={input} value={form.uom} onChange={(event) => patch({ uom: event.target.value })}>{['Job', 'Nos', 'Piece', 'KG', 'Meter', 'Other'].map((uom) => <option key={uom}>{uom}</option>)}</select></Field></>}
    <Field label={general ? 'Qty' : form.saleNature === 'yarn' ? 'Sale KG' : 'Sale Meter'}><input type="number" min="0" className={input} value={form.quantity} onChange={(event) => patch({ quantity: event.target.value })} /></Field>
    {!general && form.saleNature !== 'yarn' && <><Field label="Actual KG"><input type="number" min="0" className={input} value={form.weightKg} onChange={(event) => patch({ weightKg: event.target.value })} /></Field><Field label="Than Count"><input type="number" min="0" className={input} value={form.thanCount} onChange={(event) => patch({ thanCount: event.target.value })} /></Field>{form.saleNature === 'other' && <Field label="Piece Count"><input type="number" min="0" className={input} value={form.pieceCount} onChange={(event) => patch({ pieceCount: event.target.value })} /></Field>}</>}
    <Field label={general ? 'Rate / Amount' : t('weaving.sales.rate')}><input type="number" min="0" className={input} value={form.finalRate} onChange={(event) => patch({ finalRate: event.target.value })} /></Field>
    <Field label="Discount / Deduction"><input type="number" min="0" className={input} value={form.discountAmount} onChange={(event) => patch({ discountAmount: event.target.value })} /></Field><Field label="Tax / Charges"><input type="number" min="0" className={input} value={form.taxAmount} onChange={(event) => patch({ taxAmount: event.target.value })} /></Field><Field label={t('weaving.sales.creditDays')}><input type="number" min="0" className={input} value={form.creditDays} onChange={(event) => patch({ creditDays: event.target.value })} /></Field>
    <Field label={t('weaving.sales.saleTerms')}><select className={input} value={form.saleTerms} onChange={(event) => patch({ saleTerms: event.target.value, receivedNow: event.target.value === 'paid' ? grand : '' })}><option value="credit">Credit</option><option value="paid">Paid Now</option><option value="partial">Partial</option></select></Field>
    {form.saleTerms !== 'credit' && <><Field label={t('weaving.sales.receivedNow')}><input type="number" min="0" max={grand} disabled={form.saleTerms === 'paid'} className={input} value={form.saleTerms === 'paid' ? grand : form.receivedNow} onChange={(event) => patch({ receivedNow: event.target.value })} /></Field><Field label={t('weaving.sales.paymentAccount')}><select className={input} value={form.paymentAccountId} onChange={(event) => patch({ paymentAccountId: event.target.value })}><option value="">Select Account</option>{meta.paymentAccounts.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select></Field><Field label={t('weaving.sales.paymentMethod')}><select className={input} value={form.paymentMethod} onChange={(event) => patch({ paymentMethod: event.target.value })}><option value="cash">Cash</option><option value="bank">Bank</option><option value="online">Online</option><option value="cheque">Cheque</option></select></Field></>}
    <div className="col-span-full ml-auto w-full max-w-md rounded-md bg-teal-50 p-4"><div className="flex justify-between text-lg"><span>Grand Total</span><b>Rs. {grand.toLocaleString('en-PK')}</b></div><div className="mt-2 flex justify-between border-t pt-2"><span>Balance</span><b>Rs. {(grand - (form.saleTerms === 'paid' ? grand : Number(form.receivedNow || 0))).toLocaleString('en-PK')}</b></div></div>
    <Field label={t('weaving.sales.notes')} className="col-span-full"><textarea className={`${input} h-20 py-2`} value={form.notes} onChange={(event) => patch({ notes: event.target.value })} /></Field><div className="col-span-full flex justify-end gap-2"><button type="button" onClick={close} className="h-9 rounded-md border bg-white px-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">{t('weaving.sales.cancel')}</button><button type="button" disabled={saving} onClick={save} className="h-9 rounded-md bg-teal-700 px-3 text-sm font-semibold text-white hover:bg-teal-800 disabled:opacity-40">{saving ? t('weaving.sales.saving') : t('weaving.sales.saveDraft')}</button></div>
  </div></section></div>;
}
