import React, { useEffect, useMemo, useState } from 'react';
import { FaEdit } from 'react-icons/fa';
import { createAggregateProduction, getAggregateProductionMeta, listAggregateProduction, updateAggregateProduction, voidAggregateProduction } from '../../services/weavingFoldingService';
import { getBusinessDateInputValue } from '../../utils/localDateTime';
import { requestWeavingConfirmation, showWeavingError, showWeavingSuccess } from '../../components/weaving/WeavingFeedbackModal';

const KG_TO_LBS = 2.2046226218;
const input = 'mt-1 h-10 w-full rounded-md border border-slate-300 bg-white px-3 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100';
const empty = (keep = {}) => ({ date: keep.date || getBusinessDateInputValue(), loomId: keep.loomId || '', fabricQualityId: keep.fabricQualityId || '', meter: '', weightKg: '' });
const fmt = (value) => new Intl.NumberFormat('en-PK', { maximumFractionDigits: 3 }).format(Number(value || 0));

export default function WeavingAggregateProductionPage({ initialMeta }) {
  const [meta, setMeta] = useState(initialMeta || { settings: {}, looms: [], qualities: [] }); const [rows, setRows] = useState([]); const [form, setForm] = useState(empty()); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false);
  const mode = meta.settings?.productionTrackingMode; const loomWise = mode === 'loom_wise';
  const load = async () => { const [setup, entries] = await Promise.all([getAggregateProductionMeta(), listAggregateProduction({ date: form.date || getBusinessDateInputValue(), productionMode: mode })]); setMeta(setup); setRows(entries || []); setForm((current) => ({ ...current, loomId: setup.looms?.length === 1 ? setup.looms[0]._id : current.loomId, fabricQualityId: setup.qualities?.length === 1 ? setup.qualities[0]._id : current.fabricQualityId })); };
  useEffect(() => { load().catch((error) => showWeavingError(error, 'Could not load production.')); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const lbs = useMemo(() => Number(form.weightKg || 0) * KG_TO_LBS, [form.weightKg]);
  const save = async (event) => { event.preventDefault(); if (saving) return; setSaving(true); try { const body = { productionMode: mode, ...form }; editing ? await updateAggregateProduction(editing._id, body) : await createAggregateProduction(body); showWeavingSuccess(editing ? 'Production total updated.' : 'Production total saved.'); const keep = { date: form.date, fabricQualityId: form.fabricQualityId, loomId: meta.looms?.length === 1 ? meta.looms[0]._id : '' }; setEditing(null); setForm(empty(keep)); await load(); } catch (error) { showWeavingError(error, 'Could not save production.'); } finally { setSaving(false); } };
  const edit = (row) => { setEditing(row); setForm({ date: row.date, loomId: row.loomId?._id || row.loomId || '', fabricQualityId: row.fabricQualityId?._id || row.fabricQualityId || '', meter: row.meter, weightKg: row.weightKg }); };
  const voidRow = async (row) => { const ok = await requestWeavingConfirmation({ title: 'Void Production', text: 'Void this production total and remove its remaining stock?', confirmText: 'Void' }); if (!ok) return; try { await voidAggregateProduction(row._id, 'Voided by user'); showWeavingSuccess('Production voided.'); await load(); } catch (error) { showWeavingError(error, 'Could not void production.'); } };
  return <div className="min-h-full bg-slate-50 p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-5"><header><div className="inline-flex rounded-full bg-teal-50 px-3 py-1 text-xs font-bold text-teal-800">Production Mode: {loomWise ? 'Loom-wise' : 'Total Production'}</div><h1 className="mt-2 text-2xl font-black">Folding Production</h1><p className="mt-1 text-sm text-slate-500">Enter the current daily total. To correct it later, edit the existing row.</p></header>
    <form onSubmit={save} className="rounded-xl border bg-white p-5 shadow-sm"><div className={`grid items-end gap-4 ${loomWise ? 'md:grid-cols-6' : 'md:grid-cols-5'}`}><label className="text-sm font-bold">Date<input required type="date" className={input} value={form.date} disabled={!!editing} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label>{loomWise && <label className="text-sm font-bold">Loom<select required className={input} value={form.loomId} disabled={!!editing} onChange={(e) => setForm({ ...form, loomId: e.target.value })}><option value="">Select Loom</option>{meta.looms?.map((row) => <option key={row._id} value={row._id}>{row.loomNumber}{row.name ? ` - ${row.name}` : ''}</option>)}</select></label>}<label className="text-sm font-bold">Fabric Quality<select required className={input} value={form.fabricQualityId} disabled={!!editing} onChange={(e) => setForm({ ...form, fabricQualityId: e.target.value })}><option value="">Select Quality</option>{meta.qualities?.map((row) => <option key={row._id} value={row._id}>{row.name}{row.code ? ` - ${row.code}` : ''}</option>)}</select></label><label className="text-sm font-bold">Meter<input required min="0.000001" step="any" type="number" className={input} value={form.meter} onChange={(e) => setForm({ ...form, meter: e.target.value })} /></label><label className="text-sm font-bold">KG<input required min="0.000001" step="any" type="number" className={input} value={form.weightKg} onChange={(e) => setForm({ ...form, weightKg: e.target.value })} /></label><label className="text-sm font-bold">LBS<input readOnly className={`${input} bg-slate-100`} value={lbs ? lbs.toFixed(3) : ''} /></label><button disabled={saving} className="h-10 rounded-md bg-teal-700 px-5 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Saving…' : editing ? 'Update' : 'Save'}</button></div>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty({ date: form.date, fabricQualityId: form.fabricQualityId })); }} className="mt-3 text-sm font-bold text-slate-600">Cancel edit</button>}</form>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="border-b px-5 py-4 font-black">Today's Production</div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-100 text-left text-xs uppercase"><tr><th className="px-4 py-3">Date</th>{loomWise && <th className="px-4 py-3">Loom</th>}<th className="px-4 py-3">Quality</th><th className="px-4 py-3">Meter</th><th className="px-4 py-3">KG</th><th className="px-4 py-3">LBS</th><th className="px-4 py-3">Actions</th></tr></thead><tbody className="divide-y">{rows.map((row) => <tr key={row._id}><td className="px-4 py-3">{row.date}</td>{loomWise && <td className="px-4 py-3 font-bold">{row.loomId?.loomNumber || '-'}</td>}<td className="px-4 py-3">{row.fabricQualityId?.name || '-'}</td><td className="px-4 py-3">{fmt(row.meter)}</td><td className="px-4 py-3">{fmt(row.weightKg)}</td><td className="px-4 py-3">{fmt(row.weightLbs)}</td><td className="px-4 py-3"><button onClick={() => edit(row)} className="mr-3 text-teal-700"><FaEdit /></button><button onClick={() => voidRow(row)} className="text-rose-700">Void</button></td></tr>)}{!rows.length && <tr><td colSpan={loomWise ? 7 : 6} className="p-8 text-center text-slate-500">No production entered for today.</td></tr>}</tbody></table></div></section>
  </div></div>;
}
