import React, { useEffect, useState } from 'react';
import { FaEdit, FaWarehouse } from 'react-icons/fa';
import { t } from '../../i18n/i18n';
import WeavingFormActions from '../../components/weaving/WeavingFormActions';
import { useWeavingFeedback } from '../../components/weaving/WeavingFeedbackModal';
import { createWeavingGodown, getWeavingSettings, listWeavingGodowns, listWeavingParties, updateWeavingGodown, updateWeavingSettings } from '../../services/weavingOperationsService';

const blank = { name: '', note: '', isActive: true };
const defaults = { productionTrackingMode: 'detailed', simpleProductionOwnershipType: 'own', simpleProductionOwnerPartyId: '', simpleProductionGodownId: '' };
const modes = [
  ['detailed', 'Detailed', 'Beam / Loom / Than tracking', 'Exact Beam-to-Loom knotting and exact Than-wise Folding.'],
  ['loom_wise', 'Loom-wise Daily', 'Manual Beam ledger + daily Loom production', 'Manual Beam loading and one daily total per Loom and Quality.'],
  ['quality_total', 'Total Production', 'Manual Beam ledger + daily Quality total', 'Manual Beam loading and one daily total per Quality.'],
];
const input = 'mt-1 w-full rounded-md border border-slate-300 px-3 py-2 text-sm outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100';

export default function WeavingSettingsPage() {
  const [rows, setRows] = useState([]); const [parties, setParties] = useState([]); const [settings, setSettings] = useState(defaults);
  const [form, setForm] = useState(blank); const [editingId, setEditingId] = useState(''); const [saving, setSaving] = useState(false); const [settingsSaving, setSettingsSaving] = useState(false); const [notice, setNotice] = useState(null);
  useWeavingFeedback(notice, setNotice);
  const normalize = (value = {}) => ({ ...defaults, ...value, simpleProductionOwnerPartyId: value.simpleProductionOwnerPartyId || '', simpleProductionGodownId: value.simpleProductionGodownId || '' });
  const load = async () => { try { const [godowns, partyRows, saved] = await Promise.all([listWeavingGodowns(), listWeavingParties(), getWeavingSettings()]); setRows(godowns || []); setParties(partyRows || []); setSettings(normalize(saved)); } catch (e) { setNotice({ error: true, text: e.response?.data?.message || t('weaving.operations.loadFailed') }); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const reset = () => { setForm(blank); setEditingId(''); };
  const saveGodown = async () => { setSaving(true); try { editingId ? await updateWeavingGodown(editingId, form) : await createWeavingGodown(form); setNotice({ text: t('weaving.operations.saved') }); reset(); await load(); } catch (e) { setNotice({ error: true, text: e.response?.data?.message || t('weaving.operations.saveFailed') }); } finally { setSaving(false); } };
  const saveSettings = async () => { setSettingsSaving(true); try { setSettings(normalize(await updateWeavingSettings(settings))); setNotice({ text: 'Production settings saved.' }); } catch (e) { setNotice({ error: true, text: e.response?.data?.message || 'Could not save production settings.' }); } finally { setSettingsSaving(false); } };
  return <div className="min-h-full bg-slate-50 p-3 sm:p-6"><div className="mx-auto max-w-[1400px] space-y-5">
    <header><h1 className="text-2xl font-bold text-slate-900">{t('weaving.operations.settings')}</h1><p className="mt-1 text-sm text-slate-500">{t('weaving.operations.settingsSubtitle')}</p></header>
    <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-black">Production Tracking Method</h2><p className="mt-1 text-sm text-slate-500">This one setting controls both Knotting and Folding for new entries. Historical records are unchanged.</p><div className="mt-4 grid gap-3 lg:grid-cols-3">{modes.map(([value, title, subtitle, detail]) => <button key={value} type="button" onClick={() => setSettings({ ...settings, productionTrackingMode: value })} className={`rounded-xl border-2 p-4 text-left ${settings.productionTrackingMode === value ? 'border-teal-600 bg-teal-50 ring-2 ring-teal-100' : 'border-slate-200'}`}><div className="font-black">{title}</div><div className="mt-1 text-sm font-semibold text-teal-800">{subtitle}</div><div className="mt-2 text-xs leading-5 text-slate-600">{detail}</div></button>)}</div>
      {settings.productionTrackingMode !== 'detailed' && <div className="mt-5 grid gap-4 border-t pt-5 md:grid-cols-3"><label className="text-sm font-bold">Production Ownership<select className={input} value={settings.simpleProductionOwnershipType} onChange={(e) => setSettings({ ...settings, simpleProductionOwnershipType: e.target.value, simpleProductionOwnerPartyId: e.target.value === 'own' ? '' : settings.simpleProductionOwnerPartyId })}><option value="own">Own</option><option value="party">Party</option></select></label>{settings.simpleProductionOwnershipType === 'party' && <label className="text-sm font-bold">Production Party *<select className={input} value={settings.simpleProductionOwnerPartyId} onChange={(e) => setSettings({ ...settings, simpleProductionOwnerPartyId: e.target.value })}><option value="">Select Party</option>{parties.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select></label>}<label className="text-sm font-bold">Production Godown<select className={input} value={settings.simpleProductionGodownId} onChange={(e) => setSettings({ ...settings, simpleProductionGodownId: e.target.value })}><option value="">Folding / Unassigned</option>{rows.filter((row) => row.isActive).map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select></label></div>}
      <div className="mt-5 flex justify-end"><button disabled={settingsSaving} onClick={saveSettings} className="rounded-lg bg-teal-700 px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">{settingsSaving ? 'Saving…' : 'Save Production Settings'}</button></div>
    </section>
    <div className="grid gap-5 lg:grid-cols-[minmax(320px,440px)_1fr]"><section className="rounded-md border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">{editingId ? t('weaving.operations.editGodown') : t('weaving.operations.newGodown')}</h2></div><div className="space-y-4 p-5"><label className="block text-sm font-medium">{t('weaving.operations.godownName')} *<input className={input} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="block text-sm font-medium">{t('weaving.operations.shortNote')}<textarea rows="3" className={input} value={form.note} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm({ ...form, isActive: e.target.checked })} />{t('weaving.operations.active')}</label><WeavingFormActions editing={!!editingId} saving={saving} onSaveClose={saveGodown} onSaveNew={saveGodown} onClear={reset} onCancel={reset} /></div></section>
      <section className="overflow-hidden rounded-md border bg-white shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-bold">{t('weaving.operations.godowns')}</h2></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-100 text-left text-xs uppercase"><tr><th className="px-4 py-3">{t('weaving.operations.name')}</th><th className="px-4 py-3">{t('weaving.operations.shortNote')}</th><th className="px-4 py-3">{t('weaving.operations.status')}</th><th /></tr></thead><tbody className="divide-y">{rows.length ? rows.map((row) => <tr key={row._id}><td className="px-4 py-3 font-semibold">{row.name}</td><td className="px-4 py-3">{row.note || '-'}</td><td className="px-4 py-3">{row.isActive ? t('weaving.operations.active') : t('weaving.operations.inactive')}</td><td className="px-4 py-3 text-right"><button onClick={() => { setEditingId(row._id); setForm({ name: row.name, note: row.note, isActive: row.isActive }); }} className="p-2 text-teal-700"><FaEdit /></button></td></tr>) : <tr><td colSpan="4" className="p-10 text-center text-slate-500"><FaWarehouse className="mx-auto mb-2" />{t('weaving.operations.noRecords')}</td></tr>}</tbody></table></div></section></div>
  </div></div>;
}
