const mongoose = require("mongoose");
const lineSchema = new mongoose.Schema({
  itemKind: { type: String, enum: ["yarn", "fabric", "part", "other"], required: true },
  yarnId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingYarn", default: null },
  itemId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingItem", default: null },
  fabricQualityId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingFabricQuality", default: null },
  fabricGrade: { type: String, enum: ["normal", "b", "rejected", "cut_piece", "waste"], default: "normal" },
  weightKg: { type: Number, min: 0, default: 0 }, thanCount: { type: Number, min: 0, default: 0 }, pieceCount: { type: Number, min: 0, default: 0 },
  name: { type: String, required: true }, description: { type: String, default: "" },
  quantity: { type: Number, min: 0.000001, required: true }, unit: { type: String, required: true },
  rate: { type: Number, min: 0, required: true }, amount: { type: Number, min: 0, required: true },
  bags: { type: Number, min: 0, default: 0 },
  packageType: { type: String, enum: ["", "bag", "carton"], default: "" },
  packageQty: { type: Number, min: 0, default: 0 },
  coneSize: { type: String, enum: ["", "small", "large"], default: "" },
  conesPerPackage: { type: Number, min: 0, default: 0 },
  extraCones: { type: Number, min: 0, default: 0 },
  totalCones: { type: Number, min: 0, default: 0 },
  smallCones: { type: Number, min: 0, default: 0 },
  largeCones: { type: Number, min: 0, default: 0 },
  quantityLbs: { type: Number, min: 0, default: 0 },
  rateBasis: { type: String, enum: ["kg", "lbs"], default: "kg" },
  contractId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingContract", default: null },
  destinationType: { type: String, default: "" }, godownId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingGodown", default: null },
  sizingPartyId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingParty", default: null }, lotReference: { type: String, default: "" },
  loomId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingLoom", default: null }, nature: { type: String, enum: ["", "expense", "asset"], default: "" },
  debitAccountId: { type: mongoose.Schema.Types.ObjectId, ref: "Account", default: null },
}, { _id: true });
const schema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true },
  requestKey: { type: String, trim: true, default: null },
  replacesPurchaseId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingPurchaseInvoice", default: null },
  activeReplacementId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingPurchaseInvoice", default: null },
  moduleScope: { type: String, enum: ["weaving"], default: "weaving", immutable: true },
  purchaseNo: { type: String, required: true }, purchaseDate: { type: String, required: true },
  purchaseType: { type: String, enum: ["yarn", "fabric", "parts", "other"], required: true },
  yarnSource: { type: String, enum: ["own", "party"], default: "own" },
  partyId: { type: mongoose.Schema.Types.ObjectId, ref: "WeavingParty", required: true }, partyName: { type: String, required: true },
  supplierInvoiceNo: { type: String, default: "" }, attachmentUrl: { type: String, default: "" }, notes: { type: String, default: "" },
  dueDate: { type: String, default: "" }, creditDays: { type: Number, min: 0, default: 0 }, gatePassNo: { type: String, default: "" },
  entryMode: { type: String, enum: ["quick", "detailed"], default: "detailed" },
  quickAmount: { type: Number, min: 0, default: 0 }, quickNature: { type: String, enum: ["", "expense", "asset"], default: "" },
  quickDebitAccountId: { type: mongoose.Schema.Types.ObjectId, ref: "Account", default: null },
  attachments: { type: [{ key: String, type: String, size: Number, originalName: String }], default: [] },
  lines: [lineSchema], grandTotal: { type: Number, min: 0, default: 0 }, paidAmount: { type: Number, min: 0, default: 0 },
  balanceDue: { type: Number, min: 0, default: 0 }, paymentStatus: { type: String, enum: ["unpaid", "partial", "paid", "non_financial"], default: "unpaid" },
  purchaseJournalId: { type: mongoose.Schema.Types.ObjectId, ref: "JournalEntry", default: null },
  paymentTransactionIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "WeavingMoneyTransaction" }],
  sizingIssueIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "WeavingSizingIssue" }],
  status: { type: String, enum: ["posted", "void"], default: "posted" }, voidedAt: { type: Date, default: null },
  voidedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  voidReason: { type: String, trim: true, default: "" },
  reversalJournalIds: [{ type: mongoose.Schema.Types.ObjectId, ref: "JournalEntry" }],
}, { timestamps: true });
schema.index({ userId: 1, purchaseNo: 1 }, { unique: true });
schema.index({ userId: 1, requestKey: 1 }, { unique: true, partialFilterExpression: { requestKey: { $type: "string" } } });
schema.index({ userId: 1, partyId: 1, purchaseDate: -1 });
schema.index({ userId: 1, dueDate: 1, paymentStatus: 1, status: 1 });
module.exports = mongoose.model("WeavingPurchaseInvoice", schema);
