import {
  FaBook,
  FaChartBar,
  FaChartLine,
  FaChartPie,
  FaClipboardList,
  FaCog,
  FaCalculator,
  FaListAlt,
  FaReceipt,
  FaRoute,
  FaUndo,
  FaUserTie,
  FaUsers,
} from 'react-icons/fa';

import { MODULE_KEYS } from '../../../utils/moduleConfig';

export const travelSidebarItems = Object.freeze([
  {
    key: 'travelDashboard',
    to: '/travel/dashboard',
    labelKey: 'travel.sidebar.dashboard',
    icon: FaChartPie,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.view', 'travel.bookings.view'],
  },
  {
    key: 'travelCustomers',
    to: '/travel/customers',
    labelKey: 'travel.sidebar.customers',
    icon: FaUsers,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.bookings.view', 'travel.customers', 'travel.payments'],
  },
  {
    key: 'travelParties',
    to: '/travel/parties',
    labelKey: 'travel.sidebar.parties',
    icon: FaUsers,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.parties.view', 'travel.parties.manage'],
  },
  {
    key: 'travelVendors',
    to: '/travel/vendors',
    labelKey: 'travel.sidebar.vendors',
    icon: FaUserTie,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.vendors.view',
  },
  {
    key: 'travelTravelers',
    to: '/travel/travelers',
    labelKey: 'travel.sidebar.travelers',
    icon: FaUsers,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.travelers.view',
  },
  {
    key: 'travelBookings',
    to: '/travel/bookings',
    labelKey: 'travel.sidebar.bookings',
    icon: FaClipboardList,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.bookings.view',
  },
  {
    key: 'travelRefunds',
    to: '/travel/refunds',
    labelKey: 'travel.sidebar.refunds',
    icon: FaUndo,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.bookings.view',
  },
  {
    key: 'travelVendorReturns',
    to: '/travel/vendor-returns',
    labelKey: 'travel.sidebar.vendorReturns',
    icon: FaReceipt,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.vendors.view', 'travel.vendors.manage'],
  },
  {
    key: 'travelServices',
    to: '/travel/services',
    labelKey: 'travel.sidebar.services',
    icon: FaListAlt,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.services.view',
  },
  {
    key: 'travelTripPlanner',
    to: '/travel/trip-planner',
    labelKey: 'travel.sidebar.tripPlanner',
    icon: FaRoute,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.bookings.create', 'travel.bookings.view'],
  },
  {
    key: 'travelUmrahCalculator',
    to: '/travel/umrah-calculator',
    labelKey: 'travel.sidebar.umrahCalculator',
    icon: FaCalculator,
    module: MODULE_KEYS.TRAVEL,
    anyPermissions: ['travel.bookings.create', 'travel.bookings.view'],
  },
  {
    key: 'travelAccounts',
    to: '/travel/accounts',
    labelKey: 'travel.sidebar.accounts',
    icon: FaBook,
    module: MODULE_KEYS.TRAVEL,
    permission: 'accounts.view',
  },
  {
    key: 'travelBusinessValue',
    to: '/travel/business-value',
    labelKey: 'travel.sidebar.businessValue',
    icon: FaChartBar,
    module: MODULE_KEYS.TRAVEL,
    permission: 'business_value.view',
  },
  {
    key: 'travelReports',
    to: '/travel/reports',
    labelKey: 'travel.sidebar.reports',
    icon: FaChartLine,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.reports',
  },
  {
    key: 'travelSettings',
    to: '/travel/settings',
    labelKey: 'travel.sidebar.settings',
    icon: FaCog,
    module: MODULE_KEYS.TRAVEL,
    permission: 'travel.settings',
  },
]);
