/**
 * Customer Aging Report HTML Template
 * -----------------------------------
 * Professional accounting print layout
 * Supports A4 + A5
 */

const generateAgingReportHTML = (data, pageSize = "A5") => {
  const { documentTitle, reportDate, summary, rows } = data;

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>${documentTitle}</title>

<style>

@page {
  size: ${pageSize};
  margin: 6mm;
}

/* ===== BASE ===== */

body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: ${pageSize === "A5" ? "11px" : "13px"};
  margin: 0;
  color: #000;
}

.container {
  width: 100%;
}

/* ===== HEADER ===== */

.header {
  text-align: center;
  margin-bottom: ${pageSize === "A5" ? "8px" : "12px"};
}

.header h2 {
  margin: 0;
  font-weight: 800;
  font-size: ${pageSize === "A5" ? "16px" : "20px"};
}

.sub-info {
  margin-top: 4px;
  font-size: ${pageSize === "A5" ? "11px" : "13px"};
  font-weight: 600;
}

/* ===== SUMMARY ===== */

.summary {
  margin-top: ${pageSize === "A5" ? "6px" : "10px"};
  margin-bottom: ${pageSize === "A5" ? "8px" : "14px"};
  padding: ${pageSize === "A5" ? "4px" : "8px"};
  font-weight: 700;
  font-size: ${pageSize === "A5" ? "12px" : "15px"};
  text-align: center;
}

/* ===== TABLE ===== */

table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
  border: 2px solid #000;
}

th {
  border: 2px solid #000;
  padding: ${pageSize === "A5" ? "6px 4px" : "10px 8px"};
  text-align: center;
  font-weight: 800;
  font-size: ${pageSize === "A5" ? "12px" : "15px"};
}

td {
  border: 2px solid #000;
  padding: ${pageSize === "A5" ? "6px 4px" : "10px 8px"};
  text-align: center;
  font-weight: 600;
  word-wrap: break-word;
}

td.left {
  text-align: left;
  padding-left: 6px;
}

td.right {
  text-align: right;
  padding-right: 8px;
}

/* ===== TOTAL ROW ===== */

.totals-row {
  font-weight: 800;
  border-top: 3px solid #000;
}

/* ===== FOOTER ===== */

.footer {
  margin-top: ${pageSize === "A5" ? "10px" : "16px"};
  text-align: center;
  font-size: ${pageSize === "A5" ? "9px" : "11px"};
  border-top: 1px solid #ccc;
  padding-top: 6px;
}

</style>
</head>

<body>

<div class="container">

  <!-- HEADER -->

  <div class="header">
    <h2>${documentTitle}</h2>
    <div class="sub-info">
      Aging As Of: ${reportDate}
    </div>
  </div>

  <!-- SUMMARY -->

  <div class="summary">
    0-30: ${summary.totalRecent.toFixed(2)} |
    31-60: ${summary.totalMid1.toFixed(2)} |
    61-90: ${summary.totalMid2.toFixed(2)} |
    90+: ${summary.totalOldest.toFixed(2)} |
    Total: ${summary.grandTotal.toFixed(2)}
  </div>

  <!-- TABLE -->

  <table>

    <thead>
      <tr>
        <th style="width:30%">Customer</th>
        <th style="width:14%">0-30</th>
        <th style="width:14%">31-60</th>
        <th style="width:14%">61-90</th>
        <th style="width:14%">90+</th>
        <th style="width:14%">Total</th>
      </tr>
    </thead>

    <tbody>

      ${rows
        .map(
          (row) => `
        <tr>
          <td class="left">${row.customer}</td>
          <td class="right">${row.recent.toFixed(2)}</td>
          <td class="right">${row.mid1.toFixed(2)}</td>
          <td class="right">${row.mid2.toFixed(2)}</td>
          <td class="right">${row.oldest.toFixed(2)}</td>
          <td class="right">${row.total.toFixed(2)}</td>
        </tr>
      `,
        )
        .join("")}

      <!-- TOTALS -->

      <tr class="totals-row">
        <td class="right">Grand Total</td>
        <td>${summary.totalRecent.toFixed(2)}</td>
        <td>${summary.totalMid1.toFixed(2)}</td>
        <td>${summary.totalMid2.toFixed(2)}</td>
        <td>${summary.totalOldest.toFixed(2)}</td>
        <td>${summary.grandTotal.toFixed(2)}</td>
      </tr>

    </tbody>

  </table>

  <!-- FOOTER -->

  <div class="footer">
    Generated by SmartKhata • ${new Date().toLocaleDateString("en-GB")}
  </div>

</div>

</body>
</html>
`;
};

module.exports = generateAgingReportHTML;
