// 📁 templates/customerLedgerTemplate.js

/**
 * Customer Ledger HTML Template
 * --------------------------------
 * Professional accounting layout
 * Supports A4 + A5 (Compact A5 Version)
 */

const generateCustomerLedgerHTML = (data, pageSize = "A5") => {
  const { documentTitle, customer, period, summary, rows } = data;

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<title>${documentTitle}</title>

<style>
@page {
  size: ${pageSize};
  margin: 5mm 5mm 5mm 5mm;
}

/* ===== DYNAMIC SIZE SETTINGS ===== */

body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: ${pageSize === "A5" ? "11px" : "13px"};
  margin: 0;
  color: #000;
}

.container {
  width: 100%;
  margin: 0;
}

/* ===== HEADER ===== */

.header {
  text-align: center;
  margin-bottom: ${pageSize === "A5" ? "6px" : "12px"};
}

.header h2 {
  margin: 0;
  font-size: ${pageSize === "A5" ? "16px" : "20px"};
  font-weight: 800;
}

.sub-info {
  margin-top: 4px;
  font-size: ${pageSize === "A5" ? "11px" : "13px"};
  font-weight: 600;
}

/* ===== SUMMARY ===== */

.summary {
  margin-top: ${pageSize === "A5" ? "6px" : "10px"};
  margin-bottom: ${pageSize === "A5" ? "6px" : "12px"};
  padding: ${pageSize === "A5" ? "4px" : "8px"};
  font-weight: 900;
  font-size: ${pageSize === "A5" ? "12px" : "15px"};
}

/* ===== TABLE ===== */

table {
  width: 100%;
  border-collapse: collapse;
  table-layout: fixed;
  border: 2px solid #000; /* SAME BORDER */
}

th {
  border: 2px solid #000;
  padding: ${pageSize === "A5" ? "6px 4px" : "12px 8px"};
  text-align: center;
  vertical-align: middle;
  font-size: ${pageSize === "A5" ? "12px" : "15px"};
  font-weight: 800;
}

td {
  border: 2px solid #000;
  padding: ${pageSize === "A5" ? "6px 4px" : "10px 8px"};
  text-align: center;
  vertical-align: middle;
  font-size: ${pageSize === "A5" ? "12px" : "16px"};
  font-weight: 600;
  word-wrap: break-word;
}

td.right {
  text-align: right;
  padding-right: ${pageSize === "A5" ? "6px" : "10px"};
  font-size: ${pageSize === "A5" ? "12px" : "17px"};
  font-weight: 700;
}

td.left {
  text-align: left;
  padding-left: ${pageSize === "A5" ? "6px" : "8px"};
  font-weight: 600;
}

/* ===== TOTAL ROW ===== */

.totals-row {
  font-weight: 800;
  border-top: 3px solid #000;
}

/* ===== FOOTER ===== */

.footer {
  margin-top: ${pageSize === "A5" ? "8px" : "14px"};
  text-align: center;
  font-size: ${pageSize === "A5" ? "9px" : "11px"};
  border-top: 1px solid #ccc;
  padding-top: 6px;
}

</style>
</head>

<body>
<div class="container">

  <!-- ===== HEADER ===== -->
  <div class="header">
    <h2>${documentTitle}</h2>
    <div class="sub-info">
      Customer: ${customer.name} &nbsp;&nbsp; | &nbsp;&nbsp;
      Period: ${period.from} to ${period.to}
    </div>
  </div>

  <!-- ===== SUMMARY ===== -->
  <div class="summary">
    Opening: ${summary.opening.toFixed(2)} |
    Debit: ${summary.totalDebit.toFixed(2)} |
    Credit: ${summary.totalCredit.toFixed(2)} |
    Closing: ${
      summary.closingBalance < 0
        ? `(${Math.abs(summary.closingBalance).toFixed(2)})`
        : summary.closingBalance.toFixed(2)
    }
  </div>

  <!-- ===== TABLE ===== -->
  <table>
    <thead>
      <tr>
        <th style="width:15%">Date</th>
        <th style="width:15%">Bill No</th>
        <th style="width:25%">Source</th>
        <th style="width:15%">Debit</th>
        <th style="width:15%">Credit</th>
        <th style="width:15%">Balance</th>
      </tr>
    </thead>

    <tbody>
      ${rows
        .map(
          (row) => `
        <tr>
          <td>${row.date}</td>
          <td>${row.billNo}</td>
          <td>${row.source}</td>
          <td>${row.debit !== null ? row.debit.toFixed(2) : "-"}</td>
<td>${row.credit !== null ? row.credit.toFixed(2) : "-"}</td>
<td>${row.balance.toFixed(2)}</td>
        </tr>
      `,
        )
        .join("")}

      <!-- ===== TOTALS ===== -->
      <tr class="totals-row">
        <td colspan="3" class="right">Totals:</td>
        <td>${summary.totalDebit.toFixed(2)}</td>
<td>${summary.totalCredit.toFixed(2)}</td>
<td>${summary.closingBalance.toFixed(2)}</td>
      </tr>
    </tbody>
  </table>

  <!-- ===== FOOTER ===== -->
  <div class="footer">
    Generated by SmartKhata • ${new Date().toLocaleDateString("en-GB")}
  </div>

</div>
</body>
</html>
`;
};

module.exports = generateCustomerLedgerHTML;
